plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.4'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.green'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {

    // JSON 라이브러리
    implementation 'org.json:json:20230227'

    // DB 쿼리 로그 확인용
    implementation 'org.bgee.log4jdbc-log4j2:log4jdbc-log4j2-jdbc4:1.16'

    // LocalDateTime 처리용
    implementation 'org.mybatis:mybatis-typehandlers-jsr310:1.0.2'

    // Spring Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // MyBatis
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // 개발 편의 기능
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // DB 커넥터
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'

    // 테스트 관련
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'



}

tasks.named('test') {
    useJUnitPlatform()
}




