spring.application.name=greenShare

#spring.datasource.driverClassName=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/study_db
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mariadb://192.168.30.166:3306/team4
spring.datasource.username=team4_user

spring.datasource.password=mariadb

#\uCFFC\uB9AC\uBB38\uC774 \uC788\uB294 mapper \uD30C\uC77C \uC704\uCE58 \uC9C0\uC815, classpath\uB294 resources \uD3F4\uB354\uB97C \uC758\uBBF8\uD568
mybatis.mapper-locations=classpath:mapper/*.xml
#DB\uC5D0\uC11C \uC5B8\uB354\uC2A4\uCF54\uC5B4\uB85C \uBA85\uBA85\uB41C \uCEEC\uB7FC\uBA85\uC744 \uBCC0\uACBD
mybatis.configuration.map-underscore-to-camel-case=true
#select \uCFFC\uB9AC \uACB0\uACFC\uB97C \uAC00\uC838\uC62C DTO \uD074\uB798\uC2A4 \uD30C\uC77C\uC774 \uC120\uC5B8\uB41C \uD328\uD0A4\uC9C0\uBA85 \uC9C0\uC815
mybatis.type-aliases-package=com.green.greenshare

spring.jwt.secret=8a5b5667fe4ce868d591d6b80ae7fd95446a9d2892c7dc630f4f0d98d4a4715026dd68b851b5849e29586d11f8079e8e14ba923d2338730f1c184bd8f0c3e6b5

# src/main/resources/application.properties
weather.api.key=110b62aaa1c05a8acdfb1a5fc423c0e4
weather.api.url=https://api.openweathermap.org/data/2.5/weather



